# Generated by Django 4.2.11 on 2024-04-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_id"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
