# Generated by Django 4.2 on 2024-03-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='available_times',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
