# Generated by Django 5.0.3 on 2024-03-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Calendar", "0002_remove_calendar_available_times_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
