# Generated by Django 4.2 on 2024-04-03 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_calendar_location_alter_calendar_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='date_time',
        ),
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
