# Generated by Django 4.2 on 2024-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_remove_availability_date_time_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
