# Generated by Django 4.2 on 2024-04-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0006_rename_title_meeting_receiver_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='receiver_email',
            field=models.EmailField(max_length=254),
        ),
    ]
