# Generated by Django 4.2 on 2024-04-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Calendar", "0007_alter_meeting_receiver_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meetingavailability", old_name="calendar", new_name="meeting",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting",
                to="Calendar.calendar",
            ),
        ),
    ]
